---
#
# Ansible managed
#
repository:
  description: Install and configure virtualbox on your system.
  homepage: https://buluma.github.io/
  topics: virtualbox, system, ansible, molecule, tox, playbook
