---
image: "buluma/github-action-molecule:5.0.4"

variables:
  PY_COLORS: 1

molecule:
  stage: build
  allow_failure: false
  script:
    - image=${image} tag=${tag} molecule test
  retry: 0
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

galaxy:
  stage: deploy
  needs: []
  script:
    - ansible-galaxy role info buluma.virtualbox
