---
image: "buluma/github-action-molecule:4.0.6"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  stage: build
  allow_failure: true
  script:
    - image=${image} tag=${tag} molecule test
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

testing:
  stage: test
  needs: []
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

galaxy:
  stage: deploy
  needs: []
  script:
    - ansible-galaxy role info buluma.virtualbox

galaxy_import:
  stage: deploy
  needs: [molecule]
  script:
    - ansible-galaxy role import --api-key ${GALAXY_API_KEY} ${CI_PROJECT_PATH} --status buluma ansible-role-virtualbox
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - /
    expire_in: 1 day

role_testing:
  stage: test
  needs: []
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.virtualbox
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "latest"
      - image: "debian-systemd"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

# job_name:
# stage: .pre
# script:
#  - export
## - 'dir env:'  # Use this for PowerShell

release_job:
  stage: deploy
  needs: [molecule]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
